import { Router, Request, Response } from 'express';
import { supabase, supabaseAdmin } from '../config/supabase';
import jwt from 'jsonwebtoken';
import { env } from '../config/env';

const router = Router();

// =============================================
// Universal OTP (no Twilio / no whitelisted numbers)
// OTP is generated by our backend, stored in-memory
// with TTL, and returned to the app for display.
// In production, plug an SMS gateway here and omit
// the OTP from the response.
// =============================================
const otpStore = new Map<string, { otp: string; expiresAt: number; attempts: number }>();
const OTP_TTL = 10 * 60 * 1000; // 10 minutes
const OTP_MAX_ATTEMPTS = 5;

function normalizePhone(raw: string): string {
  const digits = String(raw || '').replace(/\D/g, '');
  if (digits.length === 10) return `+91${digits}`;
  if (digits.length === 12 && digits.startsWith('91')) return `+${digits}`;
  return `+${digits}`;
}

function generateOtp(): string {
  return String(Math.floor(100000 + Math.random() * 900000));
}

function generatePassword(): string {
  return `AqNexus${Math.random().toString(36).slice(2, 10)}${Date.now().toString(36)}1!`;
}

// Send OTP — works for ANY phone number
router.post('/send-otp', async (req: Request, res: Response) => {
  try {
    const { phone } = req.body;
    const normalized = normalizePhone(phone);
    const digits = normalized.replace(/\D/g, '');
    if (digits.length < 10 || digits.length > 12) {
      res.status(400).json({ success: false, error: { message: 'Enter a valid 10-digit mobile number' } });
      return;
    }

    const otp = generateOtp();
    otpStore.set(normalized, { otp, expiresAt: Date.now() + OTP_TTL, attempts: 0 });

    // TODO: In production, send the OTP via SMS (Twilio/MSG91/Textlocal) here.
    // Returning it in the response lets the app display it (demo/dev mode).
    res.json({
      success: true,
      message: 'OTP sent successfully',
      data: { otp, phone: normalized, expiresIn: 600 },
    });
  } catch (error: any) {
    res.status(400).json({ success: false, error: { message: error.message } });
  }
});

// Verify OTP — then create/link a real Supabase auth user by phone
router.post('/verify-otp', async (req: Request, res: Response) => {
  try {
    const { phone, otp } = req.body;
    const normalized = normalizePhone(phone);
    const entry = otpStore.get(normalized);

    if (!entry) {
      res.status(400).json({ success: false, error: { message: 'No OTP requested for this number. Request a new OTP.' } });
      return;
    }
    if (Date.now() > entry.expiresAt) {
      otpStore.delete(normalized);
      res.status(400).json({ success: false, error: { message: 'OTP expired. Request a new one.' } });
      return;
    }
    if (String(otp).trim() !== entry.otp) {
      entry.attempts += 1;
      if (entry.attempts >= OTP_MAX_ATTEMPTS) otpStore.delete(normalized);
      res.status(400).json({ success: false, error: { message: 'Invalid OTP. Try again.' } });
      return;
    }
    otpStore.delete(normalized);

    // Find or create the Supabase auth user for this phone
    const localPhone = normalized.replace('+91', '');
    let userId: string | null = null;

    // Auth uid is stored in the users table (profile-setup upserts id = auth uid)
    const { data: userRow } = await supabase
      .from('users')
      .select('id')
      .eq('phone', localPhone)
      .maybeSingle();
    if (userRow?.id) userId = userRow.id;

    // Fallback: scan auth users for a phone match
    if (!userId) {
      const { data: list } = await supabaseAdmin.auth.admin.listUsers({ page: 1, perPage: 1000 });
      const digits = normalized.replace(/\D/g, '');
      const match = list?.users?.find(u => String(u.phone || '').replace(/\D/g, '') === digits);
      if (match) userId = match.id;
    }

    if (!userId) {
      const { data: created, error: createErr } = await supabaseAdmin.auth.admin.createUser({
        phone: normalized,
        password: generatePassword(),
        phone_confirm: true,
        email_confirm: true,
      });
      if (createErr) throw createErr;
      userId = created.user!.id;
    }

    // Set a fresh password so the app can sign in via password auth
    const password = generatePassword();
    await supabaseAdmin.auth.admin.updateUserById(userId, { password });

    // Check if a profile row exists already
    const { data: user } = await supabase
      .from('users')
      .select('*')
      .eq('id', userId)
      .maybeSingle();

    const token = jwt.sign({ userId }, env.JWT_SECRET, { expiresIn: '30d' });

    res.json({
      success: true,
      data: { token, password, phone: normalized, userId, isNewUser: !user },
    });
  } catch (error: any) {
    res.status(400).json({ success: false, error: { message: error.message } });
  }
});

// Register
router.post('/register', async (req: Request, res: Response) => {
  try {
    const { phone, full_name, district, village, primary_species } = req.body;

    // Create user
    const { data: user, error: userError } = await supabase
      .from('users')
      .insert({ phone, full_name })
      .select()
      .single();

    if (userError) throw userError;

    // Create profile
    const { error: profileError } = await supabase
      .from('profiles')
      .insert({
        user_id: user.id,
        district,
        village,
        primary_species,
      });

    if (profileError) throw profileError;

    const token = jwt.sign({ userId: user.id }, env.JWT_SECRET, {
      expiresIn: '30d',
    });

    res.json({ success: true, data: { token, user } });
  } catch (error: any) {
    res.status(400).json({ success: false, error: { message: error.message } });
  }
});

// Get current user
router.get('/me', async (req: Request, res: Response) => {
  try {
    const authHeader = req.headers.authorization;
    if (!authHeader?.startsWith('Bearer ')) {
      res.status(401).json({ success: false, error: { message: 'No token' } });
      return;
    }

    const token = authHeader.split(' ')[1];
    const decoded = jwt.verify(token, env.JWT_SECRET) as { userId: string };

    const { data: user, error } = await supabase
      .from('users')
      .select('*, profiles(*)')
      .eq('id', decoded.userId)
      .single();

    if (error) throw error;

    res.json({ success: true, data: user });
  } catch (error: any) {
    res.status(400).json({ success: false, error: { message: error.message } });
  }
});

export default router;
